export const topMovies = [
  {
    Title: "The Super Mario Bros. Movie",
    Year: "2023",
    Rated: "PG",
    Released: "05 Apr 2023",
    Runtime: "92 min",
    Genre: "Animation, Adventure, Comedy",
    Director: "Aaron Horvath, Michael Jelenic, Pierre Leduc",
    Writer: "Matthew Fogel",
    Actors: "Chris Pratt, Anya Taylor-Joy, Charlie Day",
    Plot: "The story of The Super Mario Bros. on their journey through the Mushroom Kingdom.",
    Language: "English",
    Country: "United States, Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTJhNzlmNzctNTU5Yy00N2YwLThhMjQtZDM0YjEzN2Y0ZjNhXkEyXkFqcGdeQXVyMTEwMTQ4MzU5._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "56%",
      },
      {
        Source: "Metacritic",
        Value: "47/100",
      },
    ],
    Metascore: "47",
    imdbRating: "7.4",
    imdbVotes: "19,605",
    imdbID: "tt6718170",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$113,268,865",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Evil Dead Rise",
    Year: "2023",
    Rated: "R",
    Released: "21 Apr 2023",
    Runtime: "97 min",
    Genre: "Horror",
    Director: "Lee Cronin",
    Writer: "Lee Cronin",
    Actors: "Alyssa Sutherland, Lily Sullivan, Morgan Davies",
    Plot: "A twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
    Language: "English",
    Country: "New Zealand, United States, Ireland",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmZiN2VmMjktZDE5OC00ZWRmLWFlMmEtYWViMTY4NjM3ZmNkXkEyXkFqcGdeQXVyMTI2MTc2ODM3._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
      {
        Source: "Metacritic",
        Value: "71/100",
      },
    ],
    Metascore: "71",
    imdbRating: "N/A",
    imdbVotes: "924",
    imdbID: "tt13345606",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Top Gun: Maverick",
    Year: "2022",
    Rated: "PG-13",
    Released: "27 May 2022",
    Runtime: "130 min",
    Genre: "Action, Drama",
    Director: "Joseph Kosinski",
    Writer: "Jim Cash, Jack Epps Jr., Peter Craig",
    Actors: "Tom Cruise, Jennifer Connelly, Miles Teller",
    Plot: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to ...",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 87 wins & 199 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Metacritic",
        Value: "78/100",
      },
    ],
    Metascore: "78",
    imdbRating: "8.3",
    imdbVotes: "560,750",
    imdbID: "tt1745960",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$718,732,821",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "John Wick: Chapter 4",
    Year: "2023",
    Rated: "R",
    Released: "24 Mar 2023",
    Runtime: "169 min",
    Genre: "Action, Crime, Thriller",
    Director: "Chad Stahelski",
    Writer: "Shay Hatten, Michael Finch, Derek Kolstad",
    Actors: "Keanu Reeves, Laurence Fishburne, George Georgiou",
    Plot: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    Language: "English, French",
    Country: "United States, Germany",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "78/100",
      },
    ],
    Metascore: "78",
    imdbRating: "8.3",
    imdbVotes: "104,890",
    imdbID: "tt10366206",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$146,933,160",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avatar: The Way of Water",
    Year: "2022",
    Rated: "PG-13",
    Released: "16 Dec 2022",
    Runtime: "192 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "James Cameron",
    Writer: "James Cameron, Rick Jaffa, Amanda Silver",
    Actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
    Plot: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 61 wins & 120 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "76%",
      },
      {
        Source: "Metacritic",
        Value: "67/100",
      },
    ],
    Metascore: "67",
    imdbRating: "7.7",
    imdbVotes: "338,836",
    imdbID: "tt1630029",
    Type: "movie",
    DVD: "28 Mar 2023",
    BoxOffice: "$681,919,456",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Pope's Exorcist",
    Year: "2023",
    Rated: "R",
    Released: "14 Apr 2023",
    Runtime: "103 min",
    Genre: "Horror, Thriller",
    Director: "Julius Avery",
    Writer: "Michael Petroni, Evan Spiliotopoulos, R. Dean McCreary",
    Actors: "Russell Crowe, Daniel Zovatto, Alex Essoe",
    Plot: "Follow Gabriele Amorth, the Vatican's leading exorcist, as he investigates the possession of a child and uncovers a conspiracy the Vatican has tried to keep secret.",
    Language: "English, Italian, Spanish, Latin, German",
    Country: "United States, United Kingdom, Spain",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjA0MGU4MzYtYTYxMy00MjRhLTlmMDYtZTVhZDc1Y2QwNWY2XkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.2/10",
      },
      {
        Source: "Metacritic",
        Value: "45/100",
      },
    ],
    Metascore: "45",
    imdbRating: "6.2",
    imdbVotes: "9,116",
    imdbID: "tt13375076",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$15,713,875",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Renfield",
    Year: "2023",
    Rated: "R",
    Released: "14 Apr 2023",
    Runtime: "93 min",
    Genre: "Comedy, Fantasy, Horror",
    Director: "Chris McKay",
    Writer: "Ryan Ridley, Robert Kirkman",
    Actors: "Nicholas Hoult, Nicolas Cage, Awkwafina",
    Plot: "Renfield, Dracula's henchman and inmate at the lunatic asylum for decades, longs for a life away from the Count, his various demands, and all of the bloodshed that comes with them.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDIwYjVjMDMtOGYxMy00ZTRiLWE0YzktMjIwYmNhOGE4NGQ4XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Rotten Tomatoes",
        Value: "92%",
      },
    ],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "78",
    imdbID: "tt11358390",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Beau Is Afraid",
    Year: "2023",
    Rated: "R",
    Released: "21 Apr 2023",
    Runtime: "179 min",
    Genre: "Comedy, Drama, Horror",
    Director: "Ari Aster",
    Writer: "Ari Aster",
    Actors: "Joaquin Phoenix, Patti LuPone, Amy Ryan",
    Plot: "Following the sudden death of his mother, a mild-mannered but anxiety-ridden man confronts his darkest fears as he embarks on an epic, Kafkaesque odyssey back home.",
    Language: "English",
    Country: "Canada, Finland, United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTNhNWRmMDctYzE4OS00MzczLWJkODgtNzYxZTQxM2Y1YmM3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.4/10",
      },
      {
        Source: "Metacritic",
        Value: "67/100",
      },
    ],
    Metascore: "67",
    imdbRating: "7.4",
    imdbVotes: "967",
    imdbID: "tt13521006",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$320,396",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Ant-Man and the Wasp: Quantumania",
    Year: "2023",
    Rated: "PG-13",
    Released: "17 Feb 2023",
    Runtime: "124 min",
    Genre: "Action, Adventure, Comedy",
    Director: "Peyton Reed",
    Writer: "Jeff Loveness, Stan Lee, Larry Lieber",
    Actors: "Paul Rudd, Evangeline Lilly, Michael Douglas",
    Plot: "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures and embark on an adventure that goes beyond the limits of what they thought was possible.",
    Language: "English",
    Country: "United States, Australia, Canada",
    Awards: "3 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BODZhNzlmOGItMWUyYS00Y2Q5LWFlNzMtM2I2NDFkM2ZkYmE1XkEyXkFqcGdeQXVyMTU5OTA4NTIz._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
      {
        Source: "Metacritic",
        Value: "48/100",
      },
    ],
    Metascore: "48",
    imdbRating: "6.4",
    imdbVotes: "96,872",
    imdbID: "tt10954600",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$212,557,514",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Last Kingdom: Seven Kings Must Die",
    Year: "2023",
    Rated: "TV-MA",
    Released: "14 Apr 2023",
    Runtime: "111 min",
    Genre: "Action, Drama, History",
    Director: "Edward Bazalgette",
    Writer: "Martha Hillier, Bernard Cornwell",
    Actors: "Mark Rowley, Pekka Strang, Zoltan Andrasi",
    Plot: "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTlmNGE0ZGMtMzdkMC00MjQyLWI1ZjgtZTIxODAyNWJlZDFlXkEyXkFqcGdeQXVyNTQ4ODM2NjM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.3/10",
      },
      {
        Source: "Metacritic",
        Value: "45/100",
      },
    ],
    Metascore: "45",
    imdbRating: "7.3",
    imdbVotes: "8,001",
    imdbID: "tt15767808",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
